# Site title and subtitle. This is used in _includes/header.html
title: 'Pippo'
subtitle: 'Micro Java Web Framework'

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# if you use google analytics, add your tracking id here
google_analytics_id: 'UA-60911767-1'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
projecturl: 'https://github.com/pippo-java/pippo'

# Default categories (in order) to appear in the navigation
sections: [
    ['doc', 'Documentation'],
    ['tut', 'Tutorial'],
    ['mod', 'Modules'],
    ['ref', 'Reference'],
    ['dev', 'Developers'],
    ['post', 'Posts']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the redcarpet Markdown renderer
markdown: redcarpet
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]

# URL to demo source code
coreurl: 'https://github.com/pippo-java/pippo/blob/master/pippo-core'
demourl: 'https://github.com/pippo-java/pippo-demo/blob/master'
codeurl: 'https://github.com/pippo-java/pippo/blob/master'
